use_frameworks!
platform :ios, '9.0'


target 'Hyber_Example' do
  pod 'Hyber', :path => '../'
  pod 'Fabric'
      pod 'Crashlytics'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'CountryPickerSwift'

  target 'Hyber_Tests' do
    inherit! :search_paths


  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

