platform :ios, '8.0'
use_frameworks!


target 'Hyber' do
    pod 'Google/CloudMessaging'
    pod 'XCGLogger', '~> 3.3'
    pod 'DZNEmptyDataSet', '~> 1.7.3'
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end

#target 'HyberTests' do

#end
